// This file is auto generated by build/build-entry.js

import Search from "./search";

const version = "0.1.0";
const components = [Search];

const install = (Vue) => {
  components.forEach((Component) => {
    Vue.use(Component);
  });
};

if (typeof window !== "undefined" && window.Vue) {
  install(window.Vue);
}

export { install, version, Search };

export default {
  install,
  version
};
